blank_issues_enabled: false
contact_links:
  - name: Questions & discussions
    url: https://github.com/capy-school/tickets/discussions
    about: Ask questions, share ideas, or request guidance here
